### ISSUE TITLE
Iphone Ipad Issue

### ISSUE THREAD

**Issue by Event-Box** [syamilmj/Aqua-Page-Builder#177]
Hi,

accordions, toggles and tabs don't work viewing page with Iphone and Ipad, maybe also with other smartphones / tablets. You can not open them viewing the page. Only conetent of an already opened tab of an accordion is visible.
Can you please help me? 

e.g. see here: http://orbitalservice-group.com/orbitalschweissgeraete/

thanks for you help.

**Comment by Event-Box** [comment]
Could please anybody help me?!

**Comment by syamilmj** [comment]
Hi,

As it currently stands, this is an open source project and therefore we do not provide any official support for it. If you wish, you can contribute by submitting your forks, or providing initiatives of any manners for others to contribute.

Thank you
